-- Private desktop release distribution for authenticated TradeNet members.

begin;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'terminal-releases',
  'terminal-releases',
  false,
  26214400,
  array[
    'application/octet-stream',
    'application/x-msdownload',
    'application/vnd.microsoft.portable-executable'
  ]
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.terminal_releases (
  id uuid primary key default gen_random_uuid(),
  channel text not null check (channel in ('beta', 'stable')),
  version text not null,
  platform text not null check (platform in ('windows', 'macos', 'linux')),
  architecture text not null,
  bucket_id text not null default 'terminal-releases',
  object_path text not null,
  filename text not null,
  sha256 text not null check (sha256 ~ '^[a-f0-9]{64}$'),
  size_bytes bigint not null check (size_bytes > 0),
  is_active boolean not null default false,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (channel, version, platform, architecture)
);

create unique index if not exists terminal_releases_one_active_per_target
  on public.terminal_releases (channel, platform, architecture)
  where is_active;

alter table public.terminal_releases enable row level security;
revoke all on public.terminal_releases from public, anon, authenticated;

create table if not exists public.terminal_download_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  release_id uuid not null references public.terminal_releases(id) on delete restrict,
  requested_at timestamptz not null default now()
);

create index if not exists terminal_download_events_user_time_idx
  on public.terminal_download_events (user_id, requested_at desc);

alter table public.terminal_download_events enable row level security;
revoke all on public.terminal_download_events from public, anon, authenticated;

insert into public.terminal_releases (
  channel,
  version,
  platform,
  architecture,
  object_path,
  filename,
  sha256,
  size_bytes,
  is_active,
  published_at
)
values (
  'beta',
  '0.2.0-beta.14',
  'windows',
  'x86_64',
  'beta/0.2.0-beta.14/windows-x86_64/TradeNet Terminal_0.2.0-beta.14_x64-setup.exe',
  'TradeNet Terminal_0.2.0-beta.14_x64-setup.exe',
  'a87f2df8de371a8a0dbbee47e08f39e6f82eef637b02f9c86c71d10419ee3847',
  6224016,
  true,
  '2026-08-01T16:58:52Z'
)
on conflict (channel, version, platform, architecture) do update
set object_path = excluded.object_path,
    filename = excluded.filename,
    sha256 = excluded.sha256,
    size_bytes = excluded.size_bytes,
    is_active = excluded.is_active,
    published_at = excluded.published_at;

commit;
